#!/bin/sh

BASEDIR=$(dirname "$0")
PATH=$BASEDIR:$PATH

me=`basename "$0"`

function show_usage() {
	echo "Github repository local credential configurator."
	echo ""
	echo "usage: $me <username> [option]"
	echo ""
	echo "    protocol  http, https, ssh, git."
	echo "    option    -r, --recursive     Sets the submodules at them same time."
}

if [ "$#" -eq 0 ]; then
	show_usage
	exit 1
fi

if [ "$#" -lt 1 ]; then
	echo "Invalid argument list: \"$@\"."
	show_usage
	exit 1
fi

_USERNAME=''
_IS_RECURSIVE=1

# Get _USERNAME
if [ -z "$3" ]; then
	echo "No username specified."
	show_usage
	return 1
	exit 1
else
	_USERNAME="$3"
fi

# Get _IS_RECURSIVE
if [ "$4" = "-r" ]; then
	_IS_RECURSIVE=0
elif [ "$4" = "--recursive" ]; then
	_IS_RECURSIVE=0
fi

git-config-credential https github.com $_USERNAME $_IS_RECURSIVE