#!/bin/sh

export OLD_EMAIL=$1
export NEW_EMAIL=$2

git filter-branch -f --env-filter '
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]; then
    export GIT_AUTHOR_EMAIL="$NEW_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags

exit 0
